### ISSUE TITLE
Star shape

### ISSUE THREAD

**Issue by csyuhao** [elkorchi/2DGeometricShapesGenerator#1]
Why the generated images with Star shape can not fill the middle area?

**Comment by elkorchi** [comment]
@yuhaoooo I haven't thought about it, please feel free to send a pull request

**Comment by csyuhao** [comment]
I can not find any useful information about this bug. So I calculating the focus p_5 of two line(<p_0, p_2>,<p_1, p_3>), and then re-draw an triangle (p_5, p_0, p_3).
