### ISSUE TITLE
Is it possible to generate "Rectangle" shapes?

### ISSUE THREAD

**Issue by jagandecapri** [elkorchi/2DGeometricShapesGenerator#10]
Hi @elkorchi ,

I came across you [paper](https://www.sciencedirect.com/science/article/pii/S2352340920309847) and would like to use your dataset in my research work. It is very helpful. Is it possible to generate "Rectangle" shapes from the generator?

Thank you.

**Comment by elkorchi** [comment]
Hello, yes it is
